env:
  global:
    - nodejs_version=6.9.1
sudo: false

os:
  - linux
  - osx

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - nvm --version
  - nvm install $nodejs_version
  - node --version
  - npm --version
  - npm i

script:
  - npm run lint
  - npm test
