sudo: true
dist: trusty
os:
- linux
language: node_js
node_js:
- '7'
install:
- node --version
- npm --version
- npm i
- npm run build
before_deploy:
- rm -rf node_modules
deploy:
  provider: s3
  region: us-west-2
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  bucket: test-beaker-plugin-safe-authenticator
  on:
    branch: s3deploy
